MagicError: don't fail if magic number is nil
If the read file is too short (or empty), `magic` will be nil and the
`MagicError` exception itself will throw an exception because nil cannot
be formatted as an integer. Provide a more appropriate exception message
in those cases.